"""initialize car tables

Revision ID: 957232a5b7ee
Revises: 
Create Date: 2022-06-04 13:02:45.839649

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "957232a5b7ee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car",
        sa.Column(
            "id", sa.Integer(), nullable=True, autoincrement=True, unique=True
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "ad_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.Column(
            "advert_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True, default=0),
        sa.Column("make", sa.String(), nullable=True, default=""),
        sa.Column("model", sa.String(), nullable=True, default=""),
        sa.Column("color", sa.String(), nullable=True, default=""),
        sa.Column("year", sa.Integer(), nullable=True, default=0),
        sa.Column("city", sa.String(), nullable=True, default=""),
        sa.Column("post_code", sa.String(), nullable=True, default=""),
        sa.Column("mileage", sa.Integer(), nullable=True, default=0),
        sa.Column("doors", sa.Integer(), nullable=True, default=0),
        sa.Column("fuel", sa.String(), nullable=True, default=""),
        sa.Column("transmission", sa.String(), nullable=True, default=""),
        sa.Column("body_style", sa.String(), nullable=True, default=""),
        sa.Column("engine_size", sa.Integer(), nullable=True, default=0),
        sa.Column("seats", sa.Integer(), nullable=True, default=0),
        sa.Column("hero_image", sa.String(), nullable=True, default=""),
        sa.Column("date", sa.DateTime(), default=datetime.now()),
        sa.Column("car_type", sa.String(), nullable=True, default=""),
        sa.Column("dealer_domain", sa.String(), nullable=True, default=""),
        sa.Column("dealer_name", sa.String(), nullable=True, default=""),
        sa.Column("priority", sa.Integer(), nullable=True, default=0),
        sa.Column("seller_type", sa.String(), nullable=True, default=""),
        sa.Column("vrm", sa.String(), nullable=True, default=""),
        sa.Column("active", sa.Boolean(), nullable=True, default=True),
        sa.Column("created", sa.DateTime(), default=datetime.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="core",
    )
    op.create_table(
        "car_picture",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, default=True),
        sa.UniqueConstraint("id"),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["car_id"], ["core.car.id"], name="car_picture_car_id_fkey"
        ),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("car", schema="core")
    op.drop_table("car_picture", schema="core")
    # ### end Alembic commands ###